[package]
name = "srs"
version = "0.1.0"
authors = ["Ram Kaniyur <quadrupleslap@gmail.com>"]

[dependencies]
cpal = "0.8"
crossbeam-channel = "0.2"
docopt = "1"
libvpx-native-sys = "4"
opus = "0.2"
quest = "0.1"
scrap = "0.5"
serde = "1"
serde_derive = "1"
webm = "1"
