[package]
name = "srs"
description = "WebM screen recorder."
repository = "https://github.com/quadrupleslap/srs"
authors = ["Ram Kaniyur <quadrupleslap@gmail.com>"]
license = "MIT"
version = "0.2.0"

[dependencies]
env-libvpx-sys = "4.0.9"
webm = "1"

[features]
vp9 = []
