[package]
name = "record-screen"
version = "0.3.0"
authors = ["Ram Kaniyur <quadrupleslap@gmail.com>"]

[dependencies]
cpal = "0.8"
crossbeam-channel = "0.2"
docopt = "1"
env-libvpx-sys = "4.0.9"
opus = "0.2"
quest = "0.2"
sample = "0.10"
scrap = "0.5"
serde = "1"
serde_derive = "1"
webm = "1"
srs = {path = "..", version="0.2"}

[features]
default = ["vp9"]

vp9 = ["srs/vp9"]
